services:
  postgres:
    image: postgres:15
    container_name: transvestor-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: transvestor
      POSTGRES_USER: transvestor
      POSTGRES_PASSWORD: transvestor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "2020:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - my_network


volumes:
  postgres_data: 
  pgadmin_data:  
  
networks:
  my_network: