version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: transvestor-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: transvestor
      POSTGRES_USER: transvestor
      POSTGRES_PASSWORD: transvestor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 